#!/bin/bash
#==================================================================================================
#   File: 03_removeClones.sh
#   Date: May 5, 2026
#   Description: Filter clonal reads from data using Stacks clone_filter
#--------------------------------------------------------------------------------------------------
#   Author: Jared Homola
#==================================================================================================

# --- USER DEFINED VARIABLES ---
PROJ_ID=2505_mnBurbotStructure  ## Update to your MEER Lab project ID
YEAR=2025                       ## Update for the year
NETID=homolaj1                  ## Update to your MSU NetID

# --- PATH DEFINITIONS ---
MEER_DIR=/mnt/research/meerLab/$YEAR/$PROJ_ID
SCR=/mnt/gs21/scratch/$NETID/$PROJ_ID         ## May need to update "gs21"

# --- SETUP & MODULES ---
# Directories created in Step 00, but ensuring they exist for the loop
mkdir -p "$MEER_DIR/stdout/cloneFilter" "$MEER_DIR/shell/cloneFilter" "$SCR/cloneFilter"

module purge
module load Stacks/2.64-foss-2023a

# Move to the shell directory to store generated SLURM scripts
cd "$MEER_DIR/shell/cloneFilter"

# --- GENERATE AND SUBMIT CLONE FILTER JOBS ---
# Looks specifically for the .1.fq.gz files generated by demultiplexing
# Excludes remainder (.rem.) files to avoid processing low-quality fragments
ls "$SCR/demultiplex/" | grep "\.1\.fq\.gz" | grep -v "\.rem\." | sed 's/\.1\.fq\.gz//' | sort | uniq | while read -r LINE
do
  echo "Generating SLURM script for: $LINE"

  cat <<EOF > cloneFilter."$LINE".sh
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH -t 00:20:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=32G
#SBATCH -J cloneFilter.$LINE
#SBATCH -o $MEER_DIR/stdout/cloneFilter/cloneFilter.$LINE.o

# Run clone_filter on paired-end data
clone_filter \\
  -1 $SCR/demultiplex/$LINE.1.fq.gz \\
  -2 $SCR/demultiplex/$LINE.2.fq.gz \\
  -i gzfastq \\
  -o $SCR/cloneFilter/

scontrol show job \${SLURM_JOB_ID}
EOF

  sbatch cloneFilter."$LINE".sh[cite: 12]

done

module reset

echo "Clone filtering jobs submitted."